version: '3.4'
services:
  api:
    container_name: aggregator-api
    build:
      context: .
      target: developer
    ports:
      - "8080:8080"
    volumes:
      - ".:/usr/app"
    environment:
      
  mongodb:
    image: mongo:3.6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - /data/db/
    ports:
      - "8082:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8081:8081

